import { initialize, transform } from '@astrojs/compiler';
import * as esbuild from 'esbuild-wasm';

/**
 * In-browser compile + render pipeline for the docs playground.
 *
 * The compiler and esbuild run in the browser. Compiled Astro modules are
 * loaded from a Blob URL, so their runtime/library/asset imports are rewritten
 * to absolute browser URLs before the module is imported.
 *
 * This avoids relying on an import map being applied to a Blob URL.
 */

const compileReadyP = initialize({
  wasmURL: '/play/astro.wasm',
});

const esbuildReadyP = esbuild.initialize({
  wasmURL: '/play/esbuild.wasm',
  worker: false,
});

const RUNTIME_SPECIFIER = 'astro/runtime/server/index.js';
const LIBRARY_SPECIFIER = '@webf/astro-ui';
const LUCIDE_SPECIFIERS = ['lucide-astro', '@lucide/astro'];

function browserAssetUrl(path: string): string {
  return new URL(path, document.baseURI).href;
}

/**
 * Static assets imported by example snippets.
 *
 * Example:
 *
 *   import GoogleLogo from '../../assets/company-logos/google.svg';
 *
 * The compiled Astro output contains TWO imports for these assets:
 *
 *   import GoogleLogo from '../../assets/company-logos/google.svg';
 *   import * as $$module2 from '../../assets/company-logos/google.svg';
 *
 * The first import is used by the example itself.
 * The second import is generated by Astro metadata.
 *
 * Since the final example module is loaded from a Blob URL, neither relative
 * import can be resolved by the browser.
 *
 * Vite resolves these assets for us through import.meta.glob(..., { query:
 * '?url' }). We use those already-resolved browser URLs to replace the
 * imports before the Blob module is loaded.
 */
const ASSET_MODULES = import.meta.glob<string>(
  '../assets/**/*.{svg,png,jpg,jpeg,gif,webp,avif}',
  {
    eager: true,
    query: '?url',
    import: 'default',
  }
);

/**
 * Maps:
 *
 *   assets/company-logos/google.svg
 *
 * to the browser URL generated by Vite.
 */
const ASSET_URL_BY_SUFFIX = new Map<string, string>(
  Object.entries(ASSET_MODULES).map(([key, url]) => {
    const suffixIndex = key.indexOf('assets/');

    return [suffixIndex === -1 ? key : key.slice(suffixIndex), url];
  })
);

/**
 * Matches relative imports pointing into site/assets.
 *
 * This deliberately handles BOTH forms generated by Astro:
 *
 * 1. Normal/default asset import:
 *
 *    import GoogleLogo from '../../assets/company-logos/google.svg';
 *
 * 2. Astro metadata namespace import:
 *
 *    import * as $$module2 from '../../assets/company-logos/google.svg';
 *
 * The namespace import is only used by Astro's generated metadata. It does
 * not need to load the actual SVG module in the browser, so it is replaced
 * with an empty object.
 */
const RELATIVE_ASSET_IMPORT_RE =
  /import\s+(?:(\*\s+as\s+([A-Za-z_$][\w$]*))|([A-Za-z_$][\w$]*))\s+from\s+(['"])((?:\.\.?\/)+assets\/[^'"]+\.(?:svg|png|jpe?g|gif|webp|avif))\4\s*;?/g;

/**
 * Rewrites asset imports emitted by the Astro compiler.
 *
 * Default import:
 *
 *   import GoogleLogo from '../../assets/company-logos/google.svg';
 *
 * becomes:
 *
 *   const GoogleLogo = "https://.../assets/google....svg";
 *
 * Astro metadata namespace import:
 *
 *   import * as $$module2 from '../../assets/company-logos/google.svg';
 *
 * becomes:
 *
 *   const $$module2 = {};
 *
 * This is necessary because the final module is loaded from a Blob URL and
 * browsers cannot resolve relative imports from blob: URLs.
 */
function resolveAssetImports(code: string): string {
  return code.replace(
    RELATIVE_ASSET_IMPORT_RE,
    (
      _match,
      namespaceMarker,
      namespaceName,
      defaultName,
      _quote,
      specifier
    ) => {
      const suffixIndex = specifier.indexOf('assets/');
      const suffix =
        suffixIndex === -1 ? specifier : specifier.slice(suffixIndex);

      const resolved = ASSET_URL_BY_SUFFIX.get(suffix);

      if (!resolved) {
        /*
         * Leave unknown asset imports untouched.
         *
         * This allows the browser/compiler to report the original import
         * instead of silently producing an incorrect URL.
         */
        return _match;
      }

      /*
       * Astro's generated metadata imports the asset as a namespace:
       *
       *   import * as $$module2 from '...svg';
       *
       * The metadata object is not used by our minimal browser runtime, but
       * the generated module still references the binding. Keep the binding
       * valid without attempting to load the SVG as JavaScript.
       */
      if (namespaceMarker) {
        return `const ${namespaceName} = {};`;
      }

      /*
       * Normal example import:
       *
       *   import GoogleLogo from '...svg';
       *
       * CompanyLogoCard expects the logo as a string URL, so replace the
       * import with the actual Vite-generated browser URL.
       */
      return `const ${defaultName} = ${JSON.stringify(
        browserAssetUrl(resolved)
      )};`;
    }
  );
}

/**
 * Resolve the imports emitted by @astrojs/compiler to browser assets.
 *
 * The compiled example module is loaded from a Blob URL, so bare module
 * specifiers cannot rely on the page import map.
 */
function resolveBrowserImports(code: string): string {
  const runtimeUrl = browserAssetUrl('/play/astro-runtime.js');
  const libraryUrl = browserAssetUrl('/play/astro-ui.lib.js');

  return code
    .replaceAll(`"${RUNTIME_SPECIFIER}"`, JSON.stringify(runtimeUrl))
    .replaceAll(`'${RUNTIME_SPECIFIER}'`, JSON.stringify(runtimeUrl))
    .replaceAll(`"${LIBRARY_SPECIFIER}"`, JSON.stringify(libraryUrl))
    .replaceAll(`'${LIBRARY_SPECIFIER}'`, JSON.stringify(libraryUrl))
    .replaceAll(`"${LUCIDE_SPECIFIERS[0]}"`, JSON.stringify(libraryUrl))
    .replaceAll(`'${LUCIDE_SPECIFIERS[0]}'`, JSON.stringify(libraryUrl))
    .replaceAll(`"${LUCIDE_SPECIFIERS[1]}"`, JSON.stringify(libraryUrl))
    .replaceAll(`'${LUCIDE_SPECIFIERS[1]}'`, JSON.stringify(libraryUrl));
}

async function getRuntime() {
  return import(/* @vite-ignore */ browserAssetUrl('/play/astro-runtime.js'));
}

export interface CompileResult {
  code?: string;
  error?: string;
}

/**
 * Astro source -> plain JavaScript ES module.
 */
export async function compileAstroSource(
  source: string
): Promise<CompileResult> {
  try {
    await compileReadyP;

    const { code, diagnostics } = await transform(source, {
      sourcemap: false,
    });

    const fatal =
      diagnostics?.filter((diagnostic: any) => diagnostic.severity === 1) ?? [];

    if (fatal.length) {
      return {
        error: fatal.map((diagnostic: any) => diagnostic.text).join('\n'),
      };
    }

    await esbuildReadyP;

    const stripped = await esbuild.transform(code, {
      loader: 'ts',
      format: 'esm',
      target: 'esnext',
    });

    /*
     * IMPORTANT:
     *
     * Asset imports must be resolved after Astro + esbuild have generated
     * their final import statements. Astro generates additional namespace
     * imports for metadata, so resolving only the source-level import is
     * not enough.
     */
    const finalCode = resolveAssetImports(resolveBrowserImports(stripped.code));

    console.log('[playground] final compiled code:', finalCode);

    return {
      code: finalCode,
    };
  } catch (err) {
    return {
      error: err instanceof Error ? err.message : String(err),
    };
  }
}

export interface RenderResult {
  html?: string;
  error?: string;
}

/**
 * Compiled ES module -> rendered HTML.
 */
export async function renderCompiledModule(
  code: string
): Promise<RenderResult> {
  let objectUrl: string | undefined;

  try {
    const runtime = await getRuntime();

    const blob = new Blob([code], {
      type: 'text/javascript',
    });

    objectUrl = URL.createObjectURL(blob);

    const mod = await import(/* @vite-ignore */ objectUrl);

    if (typeof mod.default !== 'function') {
      return {
        error: 'This snippet has no default export to render.',
      };
    }

    const html = await runtime.renderComponentToStaticHTML(mod.default, {}, {});

    return {
      html,
    };
  } catch (err) {
    return {
      error: err instanceof Error ? err.message : String(err),
    };
  } finally {
    if (objectUrl) {
      URL.revokeObjectURL(objectUrl);
    }
  }
}

/**
 * Compile + render.
 */
export async function runAstroSource(source: string): Promise<RenderResult> {
  const compiled = await compileAstroSource(source);

  if (compiled.error || !compiled.code) {
    return {
      error: compiled.error ?? 'Compilation produced no output.',
    };
  }

  return renderCompiledModule(compiled.code);
}
